"""user status

Revision ID: cdcfb9ce1315
Revises: ddb28c93807b
Create Date: 2022-07-20 01:02:05.944244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdcfb9ce1315'
down_revision = 'ddb28c93807b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=24), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_status'))
        batch_op.drop_column('status')

    # ### end Alembic commands ###
