"""update user table

Revision ID: ddb28c93807b
Revises: b25bdbebb401
Create Date: 2022-07-20 00:46:42.934560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddb28c93807b'
down_revision = 'b25bdbebb401'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_client_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_phone'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_status'), ['status'], unique=False)

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_index('ix_student_email')
        batch_op.drop_index('ix_student_first_name')
        batch_op.drop_index('ix_student_status')

    op.drop_table('student')
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))
        batch_op.drop_column('timezone')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.String(length=500), nullable=True))
        batch_op.drop_index('ix_user_email')
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.drop_index('ix_user_username')
        batch_op.drop_column('timestamp')
        batch_op.drop_column('username')
        batch_op.drop_column('about_me')
        batch_op.drop_column('last_viewed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_viewed', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('about_me', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('timestamp', sa.DATETIME(), nullable=True))
        batch_op.create_index('ix_user_username', ['username'], unique=1)
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.create_index('ix_user_email', ['email'], unique=False)
        batch_op.drop_column('notes')
        batch_op.drop_column('is_admin')

    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timezone', sa.INTEGER(), nullable=True))
        batch_op.drop_column('is_admin')

    op.create_table('student',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('email', sa.VARCHAR(length=64), nullable=True),
    sa.Column('timezone', sa.INTEGER(), nullable=True),
    sa.Column('location', sa.VARCHAR(length=128), nullable=True),
    sa.Column('status', sa.VARCHAR(length=24), nullable=True),
    sa.Column('teacher_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.create_index('ix_student_status', ['status'], unique=False)
        batch_op.create_index('ix_student_first_name', ['first_name'], unique=False)
        batch_op.create_index('ix_student_email', ['email'], unique=False)

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_status'))
        batch_op.drop_index(batch_op.f('ix_client_phone'))
        batch_op.drop_index(batch_op.f('ix_client_first_name'))
        batch_op.drop_index(batch_op.f('ix_client_email'))

    op.drop_table('client')
    # ### end Alembic commands ###
